INSERT INTO book_booklanguage (name) VALUES ('Abkhazian');
INSERT INTO book_booklanguage (name) VALUES ('Achinese');
INSERT INTO book_booklanguage (name) VALUES ('Acoli');
INSERT INTO book_booklanguage (name) VALUES ('Adangme');
INSERT INTO book_booklanguage (name) VALUES ('Adyghe');
INSERT INTO book_booklanguage (name) VALUES ('Afar');
INSERT INTO book_booklanguage (name) VALUES ('Afrihili');
INSERT INTO book_booklanguage (name) VALUES ('Afrikaans');
INSERT INTO book_booklanguage (name) VALUES ('Aghem');
INSERT INTO book_booklanguage (name) VALUES ('Ainu');
INSERT INTO book_booklanguage (name) VALUES ('Akan');
INSERT INTO book_booklanguage (name) VALUES ('Akkadian');
INSERT INTO book_booklanguage (name) VALUES ('Akoose');
INSERT INTO book_booklanguage (name) VALUES ('Alabama');
INSERT INTO book_booklanguage (name) VALUES ('Albanian');
INSERT INTO book_booklanguage (name) VALUES ('Aleut');
INSERT INTO book_booklanguage (name) VALUES ('Algerian Arabic');
INSERT INTO book_booklanguage (name) VALUES ('Amarik');
INSERT INTO book_booklanguage (name) VALUES ('American English');
INSERT INTO book_booklanguage (name) VALUES ('American Sign Language');
INSERT INTO book_booklanguage (name) VALUES ('Ancient Egyptian');
INSERT INTO book_booklanguage (name) VALUES ('Ancient Greek');
INSERT INTO book_booklanguage (name) VALUES ('Angika');
INSERT INTO book_booklanguage (name) VALUES ('Ao Naga');
INSERT INTO book_booklanguage (name) VALUES ('Arabik');
INSERT INTO book_booklanguage (name) VALUES ('Aragonese');
INSERT INTO book_booklanguage (name) VALUES ('Aramaic');
INSERT INTO book_booklanguage (name) VALUES ('Araona');
INSERT INTO book_booklanguage (name) VALUES ('Arapaho');
INSERT INTO book_booklanguage (name) VALUES ('Arawak');
INSERT INTO book_booklanguage (name) VALUES ('Armenian');
INSERT INTO book_booklanguage (name) VALUES ('Aromanian');
INSERT INTO book_booklanguage (name) VALUES ('Arpitan');
INSERT INTO book_booklanguage (name) VALUES ('Assamese');
INSERT INTO book_booklanguage (name) VALUES ('Asturian');
INSERT INTO book_booklanguage (name) VALUES ('Asu');
INSERT INTO book_booklanguage (name) VALUES ('Atsam');
INSERT INTO book_booklanguage (name) VALUES ('Australian English');
INSERT INTO book_booklanguage (name) VALUES ('Austrian German');
INSERT INTO book_booklanguage (name) VALUES ('Avaric');
INSERT INTO book_booklanguage (name) VALUES ('Avestan');
INSERT INTO book_booklanguage (name) VALUES ('Awadhi');
INSERT INTO book_booklanguage (name) VALUES ('Aymara');
INSERT INTO book_booklanguage (name) VALUES ('Azerbaijani');
INSERT INTO book_booklanguage (name) VALUES ('Badaga');
INSERT INTO book_booklanguage (name) VALUES ('Bafia');
INSERT INTO book_booklanguage (name) VALUES ('Bafut');
INSERT INTO book_booklanguage (name) VALUES ('Bakhtiari');
INSERT INTO book_booklanguage (name) VALUES ('Balinese');
INSERT INTO book_booklanguage (name) VALUES ('Baluchi');
INSERT INTO book_booklanguage (name) VALUES ('Bambara');
INSERT INTO book_booklanguage (name) VALUES ('Bamun');
INSERT INTO book_booklanguage (name) VALUES ('Banjar');
INSERT INTO book_booklanguage (name) VALUES ('Basaa');
INSERT INTO book_booklanguage (name) VALUES ('Bashkir');
INSERT INTO book_booklanguage (name) VALUES ('Basque');
INSERT INTO book_booklanguage (name) VALUES ('Batak Toba');
INSERT INTO book_booklanguage (name) VALUES ('Bavarian');
INSERT INTO book_booklanguage (name) VALUES ('Beja');
INSERT INTO book_booklanguage (name) VALUES ('Belarus kasa');
INSERT INTO book_booklanguage (name) VALUES ('Bemba');
INSERT INTO book_booklanguage (name) VALUES ('Bena');
INSERT INTO book_booklanguage (name) VALUES ('Bengali kasa');
INSERT INTO book_booklanguage (name) VALUES ('Betawi');
INSERT INTO book_booklanguage (name) VALUES ('Bɛɛmis kasa');
INSERT INTO book_booklanguage (name) VALUES ('Bhojpuri');
INSERT INTO book_booklanguage (name) VALUES ('Bikol');
INSERT INTO book_booklanguage (name) VALUES ('Bini');
INSERT INTO book_booklanguage (name) VALUES ('Bishnupriya');
INSERT INTO book_booklanguage (name) VALUES ('Bislama');
INSERT INTO book_booklanguage (name) VALUES ('Blin');
INSERT INTO book_booklanguage (name) VALUES ('Blissymbols');
INSERT INTO book_booklanguage (name) VALUES ('Bodo');
INSERT INTO book_booklanguage (name) VALUES ('Borɔfo');
INSERT INTO book_booklanguage (name) VALUES ('Bosnian');
INSERT INTO book_booklanguage (name) VALUES ('Bɔlgeria kasa');
INSERT INTO book_booklanguage (name) VALUES ('Brahui');
INSERT INTO book_booklanguage (name) VALUES ('Braj');
INSERT INTO book_booklanguage (name) VALUES ('Brazilian Portuguese');
INSERT INTO book_booklanguage (name) VALUES ('Breton');
INSERT INTO book_booklanguage (name) VALUES ('British English');
INSERT INTO book_booklanguage (name) VALUES ('Buginese');
INSERT INTO book_booklanguage (name) VALUES ('Bulu');
INSERT INTO book_booklanguage (name) VALUES ('Buriat');
INSERT INTO book_booklanguage (name) VALUES ('Caddo');
INSERT INTO book_booklanguage (name) VALUES ('Cajun French');
INSERT INTO book_booklanguage (name) VALUES ('Canadian English');
INSERT INTO book_booklanguage (name) VALUES ('Canadian French');
INSERT INTO book_booklanguage (name) VALUES ('Cantonese');
INSERT INTO book_booklanguage (name) VALUES ('Capiznon');
INSERT INTO book_booklanguage (name) VALUES ('Carib');
INSERT INTO book_booklanguage (name) VALUES ('Catalan');
INSERT INTO book_booklanguage (name) VALUES ('Cayuga');
INSERT INTO book_booklanguage (name) VALUES ('Cebuano');
INSERT INTO book_booklanguage (name) VALUES ('Central Atlas Tamazight');
INSERT INTO book_booklanguage (name) VALUES ('Central Dusun');
INSERT INTO book_booklanguage (name) VALUES ('Central Kurdish');
INSERT INTO book_booklanguage (name) VALUES ('Central Yupik');
INSERT INTO book_booklanguage (name) VALUES ('Chadian Arabic');
INSERT INTO book_booklanguage (name) VALUES ('Chagatai');
INSERT INTO book_booklanguage (name) VALUES ('Chamorro');
INSERT INTO book_booklanguage (name) VALUES ('Chechen');
INSERT INTO book_booklanguage (name) VALUES ('Cherokee');
INSERT INTO book_booklanguage (name) VALUES ('Cheyenne');
INSERT INTO book_booklanguage (name) VALUES ('Chibcha');
INSERT INTO book_booklanguage (name) VALUES ('Chiga');
INSERT INTO book_booklanguage (name) VALUES ('Chimborazo Highland Quichua');
INSERT INTO book_booklanguage (name) VALUES ('Chinook Jargon');
INSERT INTO book_booklanguage (name) VALUES ('Chipewyan');
INSERT INTO book_booklanguage (name) VALUES ('Choctaw');
INSERT INTO book_booklanguage (name) VALUES ('Church Slavic');
INSERT INTO book_booklanguage (name) VALUES ('Chuukese');
INSERT INTO book_booklanguage (name) VALUES ('Chuvash');
INSERT INTO book_booklanguage (name) VALUES ('Classical Newari');
INSERT INTO book_booklanguage (name) VALUES ('Classical Syriac');
INSERT INTO book_booklanguage (name) VALUES ('Colognian');
INSERT INTO book_booklanguage (name) VALUES ('Comorian');
INSERT INTO book_booklanguage (name) VALUES ('Congo Swahili');
INSERT INTO book_booklanguage (name) VALUES ('Coptic');
INSERT INTO book_booklanguage (name) VALUES ('Cornish');
INSERT INTO book_booklanguage (name) VALUES ('Corsican');
INSERT INTO book_booklanguage (name) VALUES ('Cree');
INSERT INTO book_booklanguage (name) VALUES ('Creek');
INSERT INTO book_booklanguage (name) VALUES ('Crimean Turkish');
INSERT INTO book_booklanguage (name) VALUES ('Croatian');
INSERT INTO book_booklanguage (name) VALUES ('Dakota');
INSERT INTO book_booklanguage (name) VALUES ('Danish');
INSERT INTO book_booklanguage (name) VALUES ('Dargwa');
INSERT INTO book_booklanguage (name) VALUES ('Dazaga');
INSERT INTO book_booklanguage (name) VALUES ('Delaware');
INSERT INTO book_booklanguage (name) VALUES ('Dɛɛkye');
INSERT INTO book_booklanguage (name) VALUES ('Dinka');
INSERT INTO book_booklanguage (name) VALUES ('Divehi');
INSERT INTO book_booklanguage (name) VALUES ('Dogri');
INSERT INTO book_booklanguage (name) VALUES ('Dogrib');
INSERT INTO book_booklanguage (name) VALUES ('Duala');
INSERT INTO book_booklanguage (name) VALUES ('Dyula');
INSERT INTO book_booklanguage (name) VALUES ('Dzongkha');
INSERT INTO book_booklanguage (name) VALUES ('Eastern Frisian');
INSERT INTO book_booklanguage (name) VALUES ('Efik');
INSERT INTO book_booklanguage (name) VALUES ('Egyptian Arabic');
INSERT INTO book_booklanguage (name) VALUES ('Ekajuk');
INSERT INTO book_booklanguage (name) VALUES ('Elamite');
INSERT INTO book_booklanguage (name) VALUES ('Embu');
INSERT INTO book_booklanguage (name) VALUES ('Emilian');
INSERT INTO book_booklanguage (name) VALUES ('Erzya');
INSERT INTO book_booklanguage (name) VALUES ('Esperanto');
INSERT INTO book_booklanguage (name) VALUES ('Estonian');
INSERT INTO book_booklanguage (name) VALUES ('European Portuguese');
INSERT INTO book_booklanguage (name) VALUES ('European Spanish');
INSERT INTO book_booklanguage (name) VALUES ('Ewe');
INSERT INTO book_booklanguage (name) VALUES ('Ewondo');
INSERT INTO book_booklanguage (name) VALUES ('Extremaduran');
INSERT INTO book_booklanguage (name) VALUES ('Fang');
INSERT INTO book_booklanguage (name) VALUES ('Fanti');
INSERT INTO book_booklanguage (name) VALUES ('Faroese');
INSERT INTO book_booklanguage (name) VALUES ('Fiji Hindi');
INSERT INTO book_booklanguage (name) VALUES ('Fijian');
INSERT INTO book_booklanguage (name) VALUES ('Filipino');
INSERT INTO book_booklanguage (name) VALUES ('Finnish');
INSERT INTO book_booklanguage (name) VALUES ('Flemish');
INSERT INTO book_booklanguage (name) VALUES ('Fon');
INSERT INTO book_booklanguage (name) VALUES ('Frafra');
INSERT INTO book_booklanguage (name) VALUES ('Frɛnkye');
INSERT INTO book_booklanguage (name) VALUES ('Friulian');
INSERT INTO book_booklanguage (name) VALUES ('Fulah');
INSERT INTO book_booklanguage (name) VALUES ('Ga');
INSERT INTO book_booklanguage (name) VALUES ('Gagauz');
INSERT INTO book_booklanguage (name) VALUES ('Galician');
INSERT INTO book_booklanguage (name) VALUES ('Gan Chinese');
INSERT INTO book_booklanguage (name) VALUES ('Ganda');
INSERT INTO book_booklanguage (name) VALUES ('Gayo');
INSERT INTO book_booklanguage (name) VALUES ('Gbaya');
INSERT INTO book_booklanguage (name) VALUES ('Geez');
INSERT INTO book_booklanguage (name) VALUES ('Georgian');
INSERT INTO book_booklanguage (name) VALUES ('Gheg Albanian');
INSERT INTO book_booklanguage (name) VALUES ('Ghomala');
INSERT INTO book_booklanguage (name) VALUES ('Gilaki');
INSERT INTO book_booklanguage (name) VALUES ('Gilbertese');
INSERT INTO book_booklanguage (name) VALUES ('Goan Konkani');
INSERT INTO book_booklanguage (name) VALUES ('Gondi');
INSERT INTO book_booklanguage (name) VALUES ('Gorontalo');
INSERT INTO book_booklanguage (name) VALUES ('Gothic');
INSERT INTO book_booklanguage (name) VALUES ('Grebo');
INSERT INTO book_booklanguage (name) VALUES ('Greek kasa');
INSERT INTO book_booklanguage (name) VALUES ('Guarani');
INSERT INTO book_booklanguage (name) VALUES ('Gujarati');
INSERT INTO book_booklanguage (name) VALUES ('Gusii');
INSERT INTO book_booklanguage (name) VALUES ('Gwichʼin');
INSERT INTO book_booklanguage (name) VALUES ('Gyaaman');
INSERT INTO book_booklanguage (name) VALUES ('Gyabanis kasa');
INSERT INTO book_booklanguage (name) VALUES ('Gyapan kasa');
INSERT INTO book_booklanguage (name) VALUES ('Haida');
INSERT INTO book_booklanguage (name) VALUES ('Haitian');
INSERT INTO book_booklanguage (name) VALUES ('Hakka Chinese');
INSERT INTO book_booklanguage (name) VALUES ('Hangri kasa');
INSERT INTO book_booklanguage (name) VALUES ('Hausa');
INSERT INTO book_booklanguage (name) VALUES ('Hawaiian');
INSERT INTO book_booklanguage (name) VALUES ('Hebrew');
INSERT INTO book_booklanguage (name) VALUES ('Herero');
INSERT INTO book_booklanguage (name) VALUES ('Hiligaynon');
INSERT INTO book_booklanguage (name) VALUES ('Hindi');
INSERT INTO book_booklanguage (name) VALUES ('Hiri Motu');
INSERT INTO book_booklanguage (name) VALUES ('Hittite');
INSERT INTO book_booklanguage (name) VALUES ('Hmong');
INSERT INTO book_booklanguage (name) VALUES ('Hupa');
INSERT INTO book_booklanguage (name) VALUES ('Iban');
INSERT INTO book_booklanguage (name) VALUES ('Ibibio');
INSERT INTO book_booklanguage (name) VALUES ('Icelandic');
INSERT INTO book_booklanguage (name) VALUES ('Ido');
INSERT INTO book_booklanguage (name) VALUES ('Igbo');
INSERT INTO book_booklanguage (name) VALUES ('Iloko');
INSERT INTO book_booklanguage (name) VALUES ('Inari Sami');
INSERT INTO book_booklanguage (name) VALUES ('Indonihyia kasa');
INSERT INTO book_booklanguage (name) VALUES ('Ingrian');
INSERT INTO book_booklanguage (name) VALUES ('Ingush');
INSERT INTO book_booklanguage (name) VALUES ('Interlingua');
INSERT INTO book_booklanguage (name) VALUES ('Interlingue');
INSERT INTO book_booklanguage (name) VALUES ('Inuktitut');
INSERT INTO book_booklanguage (name) VALUES ('Inupiaq');
INSERT INTO book_booklanguage (name) VALUES ('Irish');
INSERT INTO book_booklanguage (name) VALUES ('Italy kasa');
INSERT INTO book_booklanguage (name) VALUES ('Jamaican Creole English');
INSERT INTO book_booklanguage (name) VALUES ('Jju');
INSERT INTO book_booklanguage (name) VALUES ('Jola-Fonyi');
INSERT INTO book_booklanguage (name) VALUES ('Judeo-Arabic');
INSERT INTO book_booklanguage (name) VALUES ('Judeo-Persian');
INSERT INTO book_booklanguage (name) VALUES ('Jutish');
INSERT INTO book_booklanguage (name) VALUES ('Kabardian');
INSERT INTO book_booklanguage (name) VALUES ('Kabuverdianu');
INSERT INTO book_booklanguage (name) VALUES ('Kabyle');
INSERT INTO book_booklanguage (name) VALUES ('Kachin');
INSERT INTO book_booklanguage (name) VALUES ('Kaingang');
INSERT INTO book_booklanguage (name) VALUES ('Kako');
INSERT INTO book_booklanguage (name) VALUES ('Kalaallisut');
INSERT INTO book_booklanguage (name) VALUES ('Kalenjin');
INSERT INTO book_booklanguage (name) VALUES ('Kalmyk');
INSERT INTO book_booklanguage (name) VALUES ('Kamba');
INSERT INTO book_booklanguage (name) VALUES ('Kambodia kasa');
INSERT INTO book_booklanguage (name) VALUES ('Kanembu');
INSERT INTO book_booklanguage (name) VALUES ('Kannada');
INSERT INTO book_booklanguage (name) VALUES ('Kanuri');
INSERT INTO book_booklanguage (name) VALUES ('Kara-Kalpak');
INSERT INTO book_booklanguage (name) VALUES ('Karachay-Balkar');
INSERT INTO book_booklanguage (name) VALUES ('Karelian');
INSERT INTO book_booklanguage (name) VALUES ('Kashmiri');
INSERT INTO book_booklanguage (name) VALUES ('Kashubian');
INSERT INTO book_booklanguage (name) VALUES ('Kawi');
INSERT INTO book_booklanguage (name) VALUES ('Kazakh');
INSERT INTO book_booklanguage (name) VALUES ('Kenyang');
INSERT INTO book_booklanguage (name) VALUES ('Khasi');
INSERT INTO book_booklanguage (name) VALUES ('Khotanese');
INSERT INTO book_booklanguage (name) VALUES ('Khowar');
INSERT INTO book_booklanguage (name) VALUES ('Kikuyu');
INSERT INTO book_booklanguage (name) VALUES ('Kimbundu');
INSERT INTO book_booklanguage (name) VALUES ('Kinaray-a');
INSERT INTO book_booklanguage (name) VALUES ('Kirmanjki');
INSERT INTO book_booklanguage (name) VALUES ('Klingon');
INSERT INTO book_booklanguage (name) VALUES ('Kom');
INSERT INTO book_booklanguage (name) VALUES ('Komi');
INSERT INTO book_booklanguage (name) VALUES ('Komi-Permyak');
INSERT INTO book_booklanguage (name) VALUES ('Kongo');
INSERT INTO book_booklanguage (name) VALUES ('Konkani');
INSERT INTO book_booklanguage (name) VALUES ('Korea kasa');
INSERT INTO book_booklanguage (name) VALUES ('Koro');
INSERT INTO book_booklanguage (name) VALUES ('Kosraean');
INSERT INTO book_booklanguage (name) VALUES ('Kotava');
INSERT INTO book_booklanguage (name) VALUES ('Koyra Chiini');
INSERT INTO book_booklanguage (name) VALUES ('Koyraboro Senni');
INSERT INTO book_booklanguage (name) VALUES ('Kpelle');
INSERT INTO book_booklanguage (name) VALUES ('Krio');
INSERT INTO book_booklanguage (name) VALUES ('Kuanyama');
INSERT INTO book_booklanguage (name) VALUES ('Kumyk');
INSERT INTO book_booklanguage (name) VALUES ('Kurdish');
INSERT INTO book_booklanguage (name) VALUES ('Kurukh');
INSERT INTO book_booklanguage (name) VALUES ('Kutenai');
INSERT INTO book_booklanguage (name) VALUES ('Kwasio');
INSERT INTO book_booklanguage (name) VALUES ('Kyaena kasa');
INSERT INTO book_booklanguage (name) VALUES ('Kyɛk kasa');
INSERT INTO book_booklanguage (name) VALUES ('Kyrgyz');
INSERT INTO book_booklanguage (name) VALUES ('Kʼicheʼ');
INSERT INTO book_booklanguage (name) VALUES ('Ladino');
INSERT INTO book_booklanguage (name) VALUES ('Lahnda');
INSERT INTO book_booklanguage (name) VALUES ('Lakota');
INSERT INTO book_booklanguage (name) VALUES ('Lamba');
INSERT INTO book_booklanguage (name) VALUES ('Langi');
INSERT INTO book_booklanguage (name) VALUES ('Lao');
INSERT INTO book_booklanguage (name) VALUES ('Latgalian');
INSERT INTO book_booklanguage (name) VALUES ('Latin');
INSERT INTO book_booklanguage (name) VALUES ('Latin American Spanish');
INSERT INTO book_booklanguage (name) VALUES ('Latvian');
INSERT INTO book_booklanguage (name) VALUES ('Laz');
INSERT INTO book_booklanguage (name) VALUES ('Lezghian');
INSERT INTO book_booklanguage (name) VALUES ('Ligurian');
INSERT INTO book_booklanguage (name) VALUES ('Limburgish');
INSERT INTO book_booklanguage (name) VALUES ('Lingala');
INSERT INTO book_booklanguage (name) VALUES ('Lingua Franca Nova');
INSERT INTO book_booklanguage (name) VALUES ('Literary Chinese');
INSERT INTO book_booklanguage (name) VALUES ('Lithuanian');
INSERT INTO book_booklanguage (name) VALUES ('Livonian');
INSERT INTO book_booklanguage (name) VALUES ('Lojban');
INSERT INTO book_booklanguage (name) VALUES ('Lombard');
INSERT INTO book_booklanguage (name) VALUES ('Low German');
INSERT INTO book_booklanguage (name) VALUES ('Lower Silesian');
INSERT INTO book_booklanguage (name) VALUES ('Lower Sorbian');
INSERT INTO book_booklanguage (name) VALUES ('Lozi');
INSERT INTO book_booklanguage (name) VALUES ('Luba-Katanga');
INSERT INTO book_booklanguage (name) VALUES ('Luba-Lulua');
INSERT INTO book_booklanguage (name) VALUES ('Luiseno');
INSERT INTO book_booklanguage (name) VALUES ('Lule Sami');
INSERT INTO book_booklanguage (name) VALUES ('Lunda');
INSERT INTO book_booklanguage (name) VALUES ('Luo');
INSERT INTO book_booklanguage (name) VALUES ('Luxembourgish');
INSERT INTO book_booklanguage (name) VALUES ('Luyia');
INSERT INTO book_booklanguage (name) VALUES ('Maba');
INSERT INTO book_booklanguage (name) VALUES ('Macedonian');
INSERT INTO book_booklanguage (name) VALUES ('Machame');
INSERT INTO book_booklanguage (name) VALUES ('Madurese');
INSERT INTO book_booklanguage (name) VALUES ('Mafa');
INSERT INTO book_booklanguage (name) VALUES ('Magahi');
INSERT INTO book_booklanguage (name) VALUES ('Main-Franconian');
INSERT INTO book_booklanguage (name) VALUES ('Maithili');
INSERT INTO book_booklanguage (name) VALUES ('Makasar');
INSERT INTO book_booklanguage (name) VALUES ('Makhuwa-Meetto');
INSERT INTO book_booklanguage (name) VALUES ('Makonde');
INSERT INTO book_booklanguage (name) VALUES ('Malagasy');
INSERT INTO book_booklanguage (name) VALUES ('Malay kasa');
INSERT INTO book_booklanguage (name) VALUES ('Malayalam');
INSERT INTO book_booklanguage (name) VALUES ('Maltese');
INSERT INTO book_booklanguage (name) VALUES ('Manchu');
INSERT INTO book_booklanguage (name) VALUES ('Mandar');
INSERT INTO book_booklanguage (name) VALUES ('Mandingo');
INSERT INTO book_booklanguage (name) VALUES ('Manipuri');
INSERT INTO book_booklanguage (name) VALUES ('Manx');
INSERT INTO book_booklanguage (name) VALUES ('Maori');
INSERT INTO book_booklanguage (name) VALUES ('Mapuche');
INSERT INTO book_booklanguage (name) VALUES ('Marathi');
INSERT INTO book_booklanguage (name) VALUES ('Mari');
INSERT INTO book_booklanguage (name) VALUES ('Marshallese');
INSERT INTO book_booklanguage (name) VALUES ('Marwari');
INSERT INTO book_booklanguage (name) VALUES ('Masai');
INSERT INTO book_booklanguage (name) VALUES ('Mazanderani');
INSERT INTO book_booklanguage (name) VALUES ('Medumba');
INSERT INTO book_booklanguage (name) VALUES ('Mende');
INSERT INTO book_booklanguage (name) VALUES ('Mentawai');
INSERT INTO book_booklanguage (name) VALUES ('Meru');
INSERT INTO book_booklanguage (name) VALUES ('Metaʼ');
INSERT INTO book_booklanguage (name) VALUES ('Mexican Spanish');
INSERT INTO book_booklanguage (name) VALUES ('Micmac');
INSERT INTO book_booklanguage (name) VALUES ('Middle Dutch');
INSERT INTO book_booklanguage (name) VALUES ('Middle English');
INSERT INTO book_booklanguage (name) VALUES ('Middle French');
INSERT INTO book_booklanguage (name) VALUES ('Middle High German');
INSERT INTO book_booklanguage (name) VALUES ('Middle Irish');
INSERT INTO book_booklanguage (name) VALUES ('Min Nan Chinese');
INSERT INTO book_booklanguage (name) VALUES ('Minangkabau');
INSERT INTO book_booklanguage (name) VALUES ('Mingrelian');
INSERT INTO book_booklanguage (name) VALUES ('Mirandese');
INSERT INTO book_booklanguage (name) VALUES ('Mizo');
INSERT INTO book_booklanguage (name) VALUES ('Modern Standard Arabic');
INSERT INTO book_booklanguage (name) VALUES ('Mohawk');
INSERT INTO book_booklanguage (name) VALUES ('Moksha');
INSERT INTO book_booklanguage (name) VALUES ('Moldavian');
INSERT INTO book_booklanguage (name) VALUES ('Mongo');
INSERT INTO book_booklanguage (name) VALUES ('Mongolian');
INSERT INTO book_booklanguage (name) VALUES ('Morisyen');
INSERT INTO book_booklanguage (name) VALUES ('Moroccan Arabic');
INSERT INTO book_booklanguage (name) VALUES ('Mossi');
INSERT INTO book_booklanguage (name) VALUES ('Multiple Languages');
INSERT INTO book_booklanguage (name) VALUES ('Mundang');
INSERT INTO book_booklanguage (name) VALUES ('Muslim Tat');
INSERT INTO book_booklanguage (name) VALUES ('Myene');
INSERT INTO book_booklanguage (name) VALUES ('Nama');
INSERT INTO book_booklanguage (name) VALUES ('Nauru');
INSERT INTO book_booklanguage (name) VALUES ('Navajo');
INSERT INTO book_booklanguage (name) VALUES ('Ndonga');
INSERT INTO book_booklanguage (name) VALUES ('Neapolitan');
INSERT INTO book_booklanguage (name) VALUES ('Newari');
INSERT INTO book_booklanguage (name) VALUES ('Nɛpal kasa');
INSERT INTO book_booklanguage (name) VALUES ('Ngambay');
INSERT INTO book_booklanguage (name) VALUES ('Ngiemboon');
INSERT INTO book_booklanguage (name) VALUES ('Ngomba');
INSERT INTO book_booklanguage (name) VALUES ('Nheengatu');
INSERT INTO book_booklanguage (name) VALUES ('Nias');
INSERT INTO book_booklanguage (name) VALUES ('Niuean');
INSERT INTO book_booklanguage (name) VALUES ('No linguistic content');
INSERT INTO book_booklanguage (name) VALUES ('Nogai');
INSERT INTO book_booklanguage (name) VALUES ('North Ndebele');
INSERT INTO book_booklanguage (name) VALUES ('Northern Frisian');
INSERT INTO book_booklanguage (name) VALUES ('Northern Sami');
INSERT INTO book_booklanguage (name) VALUES ('Northern Sotho');
INSERT INTO book_booklanguage (name) VALUES ('Norwegian');
INSERT INTO book_booklanguage (name) VALUES ('Norwegian Bokmål');
INSERT INTO book_booklanguage (name) VALUES ('Norwegian Nynorsk');
INSERT INTO book_booklanguage (name) VALUES ('Novial');
INSERT INTO book_booklanguage (name) VALUES ('Nuer');
INSERT INTO book_booklanguage (name) VALUES ('Nyamwezi');
INSERT INTO book_booklanguage (name) VALUES ('Nyanja');
INSERT INTO book_booklanguage (name) VALUES ('Nyankole');
INSERT INTO book_booklanguage (name) VALUES ('Nyasa Tonga');
INSERT INTO book_booklanguage (name) VALUES ('Nyoro');
INSERT INTO book_booklanguage (name) VALUES ('Nzima');
INSERT INTO book_booklanguage (name) VALUES ('NʼKo');
INSERT INTO book_booklanguage (name) VALUES ('Occitan');
INSERT INTO book_booklanguage (name) VALUES ('Ojibwa');
INSERT INTO book_booklanguage (name) VALUES ('Old English');
INSERT INTO book_booklanguage (name) VALUES ('Old French');
INSERT INTO book_booklanguage (name) VALUES ('Old High German');
INSERT INTO book_booklanguage (name) VALUES ('Old Irish');
INSERT INTO book_booklanguage (name) VALUES ('Old Norse');
INSERT INTO book_booklanguage (name) VALUES ('Old Persian');
INSERT INTO book_booklanguage (name) VALUES ('Old Provençal');
INSERT INTO book_booklanguage (name) VALUES ('Oriya');
INSERT INTO book_booklanguage (name) VALUES ('Oromo');
INSERT INTO book_booklanguage (name) VALUES ('Osage');
INSERT INTO book_booklanguage (name) VALUES ('Ossetic');
INSERT INTO book_booklanguage (name) VALUES ('Ottoman Turkish');
INSERT INTO book_booklanguage (name) VALUES ('Pahlavi');
INSERT INTO book_booklanguage (name) VALUES ('Palatine German');
INSERT INTO book_booklanguage (name) VALUES ('Palauan');
INSERT INTO book_booklanguage (name) VALUES ('Pali');
INSERT INTO book_booklanguage (name) VALUES ('Pampanga');
INSERT INTO book_booklanguage (name) VALUES ('Pangasinan');
INSERT INTO book_booklanguage (name) VALUES ('Papiamento');
INSERT INTO book_booklanguage (name) VALUES ('Pashto');
INSERT INTO book_booklanguage (name) VALUES ('Pennsylvania German');
INSERT INTO book_booklanguage (name) VALUES ('Pɛɛhyia kasa');
INSERT INTO book_booklanguage (name) VALUES ('Phoenician');
INSERT INTO book_booklanguage (name) VALUES ('Picard');
INSERT INTO book_booklanguage (name) VALUES ('Piedmontese');
INSERT INTO book_booklanguage (name) VALUES ('Plautdietsch');
INSERT INTO book_booklanguage (name) VALUES ('Pohnpeian');
INSERT INTO book_booklanguage (name) VALUES ('Pontic');
INSERT INTO book_booklanguage (name) VALUES ('Pɔland kasa');
INSERT INTO book_booklanguage (name) VALUES ('Pɔɔtugal kasa');
INSERT INTO book_booklanguage (name) VALUES ('Prussian');
INSERT INTO book_booklanguage (name) VALUES ('Pungyabi kasa');
INSERT INTO book_booklanguage (name) VALUES ('Quechua');
INSERT INTO book_booklanguage (name) VALUES ('Rahyia kasa');
INSERT INTO book_booklanguage (name) VALUES ('Rajasthani');
INSERT INTO book_booklanguage (name) VALUES ('Rapanui');
INSERT INTO book_booklanguage (name) VALUES ('Rarotongan');
INSERT INTO book_booklanguage (name) VALUES ('Rewanda kasa');
INSERT INTO book_booklanguage (name) VALUES ('Riffian');
INSERT INTO book_booklanguage (name) VALUES ('Romagnol');
INSERT INTO book_booklanguage (name) VALUES ('Romansh');
INSERT INTO book_booklanguage (name) VALUES ('Romany');
INSERT INTO book_booklanguage (name) VALUES ('Rombo');
INSERT INTO book_booklanguage (name) VALUES ('Romenia kasa');
INSERT INTO book_booklanguage (name) VALUES ('Root');
INSERT INTO book_booklanguage (name) VALUES ('Rotuman');
INSERT INTO book_booklanguage (name) VALUES ('Roviana');
INSERT INTO book_booklanguage (name) VALUES ('Rundi');
INSERT INTO book_booklanguage (name) VALUES ('Rusyn');
INSERT INTO book_booklanguage (name) VALUES ('Rwa');
INSERT INTO book_booklanguage (name) VALUES ('Saho');
INSERT INTO book_booklanguage (name) VALUES ('Sakha');
INSERT INTO book_booklanguage (name) VALUES ('Samaritan Aramaic');
INSERT INTO book_booklanguage (name) VALUES ('Samburu');
INSERT INTO book_booklanguage (name) VALUES ('Samoan');
INSERT INTO book_booklanguage (name) VALUES ('Samogitian');
INSERT INTO book_booklanguage (name) VALUES ('Sandawe');
INSERT INTO book_booklanguage (name) VALUES ('Sango');
INSERT INTO book_booklanguage (name) VALUES ('Sangu');
INSERT INTO book_booklanguage (name) VALUES ('Sanskrit');
INSERT INTO book_booklanguage (name) VALUES ('Santali');
INSERT INTO book_booklanguage (name) VALUES ('Sardinian');
INSERT INTO book_booklanguage (name) VALUES ('Sasak');
INSERT INTO book_booklanguage (name) VALUES ('Sassarese Sardinian');
INSERT INTO book_booklanguage (name) VALUES ('Saterland Frisian');
INSERT INTO book_booklanguage (name) VALUES ('Saurashtra');
INSERT INTO book_booklanguage (name) VALUES ('Scots');
INSERT INTO book_booklanguage (name) VALUES ('Scottish Gaelic');
INSERT INTO book_booklanguage (name) VALUES ('Selayar');
INSERT INTO book_booklanguage (name) VALUES ('Selkup');
INSERT INTO book_booklanguage (name) VALUES ('Sena');
INSERT INTO book_booklanguage (name) VALUES ('Seneca');
INSERT INTO book_booklanguage (name) VALUES ('Serbian');
INSERT INTO book_booklanguage (name) VALUES ('Serbo-Croatian');
INSERT INTO book_booklanguage (name) VALUES ('Serer');
INSERT INTO book_booklanguage (name) VALUES ('Seri');
INSERT INTO book_booklanguage (name) VALUES ('Shambala');
INSERT INTO book_booklanguage (name) VALUES ('Shan');
INSERT INTO book_booklanguage (name) VALUES ('Shona');
INSERT INTO book_booklanguage (name) VALUES ('Sichuan Yi');
INSERT INTO book_booklanguage (name) VALUES ('Sicilian');
INSERT INTO book_booklanguage (name) VALUES ('Sidamo');
INSERT INTO book_booklanguage (name) VALUES ('Siksika');
INSERT INTO book_booklanguage (name) VALUES ('Silesian');
INSERT INTO book_booklanguage (name) VALUES ('Simplified Chinese');
INSERT INTO book_booklanguage (name) VALUES ('Sindhi');
INSERT INTO book_booklanguage (name) VALUES ('Sinhala');
INSERT INTO book_booklanguage (name) VALUES ('Skolt Sami');
INSERT INTO book_booklanguage (name) VALUES ('Slave');
INSERT INTO book_booklanguage (name) VALUES ('Slovak');
INSERT INTO book_booklanguage (name) VALUES ('Slovenian');
INSERT INTO book_booklanguage (name) VALUES ('Soga');
INSERT INTO book_booklanguage (name) VALUES ('Sogdien');
INSERT INTO book_booklanguage (name) VALUES ('Somalia kasa');
INSERT INTO book_booklanguage (name) VALUES ('Soninke');
INSERT INTO book_booklanguage (name) VALUES ('South Azerbaijani');
INSERT INTO book_booklanguage (name) VALUES ('South Ndebele');
INSERT INTO book_booklanguage (name) VALUES ('Southern Altai');
INSERT INTO book_booklanguage (name) VALUES ('Southern Sami');
INSERT INTO book_booklanguage (name) VALUES ('Southern Sotho');
INSERT INTO book_booklanguage (name) VALUES ('Spain kasa');
INSERT INTO book_booklanguage (name) VALUES ('Sranan Tongo');
INSERT INTO book_booklanguage (name) VALUES ('Standard Moroccan Tamazight');
INSERT INTO book_booklanguage (name) VALUES ('Sukuma');
INSERT INTO book_booklanguage (name) VALUES ('Sumerian');
INSERT INTO book_booklanguage (name) VALUES ('Sundanese');
INSERT INTO book_booklanguage (name) VALUES ('Susu');
INSERT INTO book_booklanguage (name) VALUES ('Swahili');
INSERT INTO book_booklanguage (name) VALUES ('Swati');
INSERT INTO book_booklanguage (name) VALUES ('Sweden kasa');
INSERT INTO book_booklanguage (name) VALUES ('Swiss French');
INSERT INTO book_booklanguage (name) VALUES ('Swiss German');
INSERT INTO book_booklanguage (name) VALUES ('Swiss High German');
INSERT INTO book_booklanguage (name) VALUES ('Syriac');
INSERT INTO book_booklanguage (name) VALUES ('Tachelhit');
INSERT INTO book_booklanguage (name) VALUES ('Taeland kasa');
INSERT INTO book_booklanguage (name) VALUES ('Tagalog');
INSERT INTO book_booklanguage (name) VALUES ('Tahitian');
INSERT INTO book_booklanguage (name) VALUES ('Taita');
INSERT INTO book_booklanguage (name) VALUES ('Tajik');
INSERT INTO book_booklanguage (name) VALUES ('Talysh');
INSERT INTO book_booklanguage (name) VALUES ('Tamashek');
INSERT INTO book_booklanguage (name) VALUES ('Tamil kasa');
INSERT INTO book_booklanguage (name) VALUES ('Taroko');
INSERT INTO book_booklanguage (name) VALUES ('Tasawaq');
INSERT INTO book_booklanguage (name) VALUES ('Tatar');
INSERT INTO book_booklanguage (name) VALUES ('Telugu');
INSERT INTO book_booklanguage (name) VALUES ('Tereno');
INSERT INTO book_booklanguage (name) VALUES ('Teso');
INSERT INTO book_booklanguage (name) VALUES ('Tetum');
INSERT INTO book_booklanguage (name) VALUES ('Tɛɛki kasa');
INSERT INTO book_booklanguage (name) VALUES ('Tibetan');
INSERT INTO book_booklanguage (name) VALUES ('Tigre');
INSERT INTO book_booklanguage (name) VALUES ('Tigrinya');
INSERT INTO book_booklanguage (name) VALUES ('Timne');
INSERT INTO book_booklanguage (name) VALUES ('Tiv');
INSERT INTO book_booklanguage (name) VALUES ('Tlingit');
INSERT INTO book_booklanguage (name) VALUES ('Tok Pisin');
INSERT INTO book_booklanguage (name) VALUES ('Tokelau');
INSERT INTO book_booklanguage (name) VALUES ('Tongan');
INSERT INTO book_booklanguage (name) VALUES ('Tornedalen Finnish');
INSERT INTO book_booklanguage (name) VALUES ('Traditional Chinese');
INSERT INTO book_booklanguage (name) VALUES ('Tsakhur');
INSERT INTO book_booklanguage (name) VALUES ('Tsakonian');
INSERT INTO book_booklanguage (name) VALUES ('Tsimshian');
INSERT INTO book_booklanguage (name) VALUES ('Tsonga');
INSERT INTO book_booklanguage (name) VALUES ('Tswana');
INSERT INTO book_booklanguage (name) VALUES ('Tulu');
INSERT INTO book_booklanguage (name) VALUES ('Tumbuka');
INSERT INTO book_booklanguage (name) VALUES ('Tunisian Arabic');
INSERT INTO book_booklanguage (name) VALUES ('Turkmen');
INSERT INTO book_booklanguage (name) VALUES ('Turoyo');
INSERT INTO book_booklanguage (name) VALUES ('Tuvalu');
INSERT INTO book_booklanguage (name) VALUES ('Tuvinian');
INSERT INTO book_booklanguage (name) VALUES ('Twi');
INSERT INTO book_booklanguage (name) VALUES ('Tyap');
INSERT INTO book_booklanguage (name) VALUES ('Udmurt');
INSERT INTO book_booklanguage (name) VALUES ('Ugaritic');
INSERT INTO book_booklanguage (name) VALUES ('Ukren kasa');
INSERT INTO book_booklanguage (name) VALUES ('Umbundu');
INSERT INTO book_booklanguage (name) VALUES ('Unknown Language');
INSERT INTO book_booklanguage (name) VALUES ('Upper Sorbian');
INSERT INTO book_booklanguage (name) VALUES ('Urdu kasa');
INSERT INTO book_booklanguage (name) VALUES ('Uyghur');
INSERT INTO book_booklanguage (name) VALUES ('Uzbek');
INSERT INTO book_booklanguage (name) VALUES ('Vai');
INSERT INTO book_booklanguage (name) VALUES ('Venda');
INSERT INTO book_booklanguage (name) VALUES ('Venetian');
INSERT INTO book_booklanguage (name) VALUES ('Veps');
INSERT INTO book_booklanguage (name) VALUES ('Viɛtnam kasa');
INSERT INTO book_booklanguage (name) VALUES ('Volapük');
INSERT INTO book_booklanguage (name) VALUES ('Võro');
INSERT INTO book_booklanguage (name) VALUES ('Votic');
INSERT INTO book_booklanguage (name) VALUES ('Vunjo');
INSERT INTO book_booklanguage (name) VALUES ('Walloon');
INSERT INTO book_booklanguage (name) VALUES ('Walser');
INSERT INTO book_booklanguage (name) VALUES ('Waray');
INSERT INTO book_booklanguage (name) VALUES ('Warlpiri');
INSERT INTO book_booklanguage (name) VALUES ('Washo');
INSERT INTO book_booklanguage (name) VALUES ('Wayuu');
INSERT INTO book_booklanguage (name) VALUES ('Welsh');
INSERT INTO book_booklanguage (name) VALUES ('West Flemish');
INSERT INTO book_booklanguage (name) VALUES ('Western Frisian');
INSERT INTO book_booklanguage (name) VALUES ('Western Mari');
INSERT INTO book_booklanguage (name) VALUES ('Wolaytta');
INSERT INTO book_booklanguage (name) VALUES ('Wolof');
INSERT INTO book_booklanguage (name) VALUES ('Wu Chinese');
INSERT INTO book_booklanguage (name) VALUES ('Xhosa');
INSERT INTO book_booklanguage (name) VALUES ('Xiang Chinese');
INSERT INTO book_booklanguage (name) VALUES ('Yangben');
INSERT INTO book_booklanguage (name) VALUES ('Yao');
INSERT INTO book_booklanguage (name) VALUES ('Yapese');
INSERT INTO book_booklanguage (name) VALUES ('Yemba');
INSERT INTO book_booklanguage (name) VALUES ('Yiddish');
INSERT INTO book_booklanguage (name) VALUES ('Yoruba');
INSERT INTO book_booklanguage (name) VALUES ('Zapotec');
INSERT INTO book_booklanguage (name) VALUES ('Zarma');
INSERT INTO book_booklanguage (name) VALUES ('Zaza');
INSERT INTO book_booklanguage (name) VALUES ('Zeelandic');
INSERT INTO book_booklanguage (name) VALUES ('Zenaga');
INSERT INTO book_booklanguage (name) VALUES ('Zhuang');
INSERT INTO book_booklanguage (name) VALUES ('Zoroastrian Dari');
INSERT INTO book_booklanguage (name) VALUES ('Zulu');
INSERT INTO book_booklanguage (name) VALUES ('Zuni');
