INSERT INTO book_booktopic (name) VALUES ('AI');
INSERT INTO book_booktopic (name) VALUES ('IT and Society');
INSERT INTO book_booktopic (name) VALUES ('Free and Open Source Software');
INSERT INTO book_booktopic (name) VALUES ('Biographies');
INSERT INTO book_booktopic (name) VALUES ('Media and Information Theory');
INSERT INTO book_booktopic (name) VALUES ('Problems of IT Practices');
INSERT INTO book_booktopic (name) VALUES ('Philosophy');
INSERT INTO book_booktopic (name) VALUES ('Philosophy and Ethics of Technology');
INSERT INTO book_booktopic (name) VALUES ('Philosophy / Methodology / Reasoning');
INSERT INTO book_booktopic (name) VALUES ('Reflective practice');
INSERT INTO book_booktopic (name) VALUES ('Web / Critical theory');
INSERT INTO book_booktopic (name) VALUES ('Critical Theory');
INSERT INTO book_booktopic (name) VALUES ('Communication');
INSERT INTO book_booktopic (name) VALUES ('Innovation');
INSERT INTO book_booktopic (name) VALUES ('Cyberpsychology');
INSERT INTO book_booktopic (name) VALUES ('Society');
INSERT INTO book_booktopic (name) VALUES ('New Economy');
INSERT INTO book_booktopic (name) VALUES ('Language and Thought');
INSERT INTO book_booktopic (name) VALUES ('Ethics');
INSERT INTO book_booktopic (name) VALUES ('Agile Software Craftsmenship');
INSERT INTO book_booktopic (name) VALUES ('JavaScript');
INSERT INTO book_booktopic (name) VALUES ('Basics on OO paradigma');
INSERT INTO book_booktopic (name) VALUES ('Software Quality');
INSERT INTO book_booktopic (name) VALUES ('OO');
INSERT INTO book_booktopic (name) VALUES ('Functional Programming');
INSERT INTO book_booktopic (name) VALUES ('Data Science');
INSERT INTO book_booktopic (name) VALUES ('Machine Learning');
INSERT INTO book_booktopic (name) VALUES ('Theoretical Computer Science');
INSERT INTO book_booktopic (name) VALUES ('RDBMS');
INSERT INTO book_booktopic (name) VALUES ('NoSQL');
INSERT INTO book_booktopic (name) VALUES ('Key Value DB');
INSERT INTO book_booktopic (name) VALUES ('Big Data');
INSERT INTO book_booktopic (name) VALUES ('Database');
INSERT INTO book_booktopic (name) VALUES ('IoT');
INSERT INTO book_booktopic (name) VALUES ('HA');
INSERT INTO book_booktopic (name) VALUES ('DevOps');
INSERT INTO book_booktopic (name) VALUES ('Mobile');
INSERT INTO book_booktopic (name) VALUES ('Software Architecture');
INSERT INTO book_booktopic (name) VALUES ('Design Patterns');
INSERT INTO book_booktopic (name) VALUES ('Cryptography');
INSERT INTO book_booktopic (name) VALUES ('Security');
INSERT INTO book_booktopic (name) VALUES ('Blockchain');
INSERT INTO book_booktopic (name) VALUES ('Algorithms & Math');
INSERT INTO book_booktopic (name) VALUES ('Planing & QA');
INSERT INTO book_booktopic (name) VALUES ('Continious Integration');
INSERT INTO book_booktopic (name) VALUES ('Testing');
INSERT INTO book_booktopic (name) VALUES ('Programming Languages / Scripting');
INSERT INTO book_booktopic (name) VALUES ('Experience Design / Theory');
INSERT INTO book_booktopic (name) VALUES ('Experience Design');
INSERT INTO book_booktopic (name) VALUES ('User Experience');
INSERT INTO book_booktopic (name) VALUES ('Product development process');
INSERT INTO book_booktopic (name) VALUES ('User Research');
INSERT INTO book_booktopic (name) VALUES ('Usability');
INSERT INTO book_booktopic (name) VALUES ('A/B testing, Web tracking');
INSERT INTO book_booktopic (name) VALUES ('Design Research');
INSERT INTO book_booktopic (name) VALUES ('Design Research practical tools & methods');
INSERT INTO book_booktopic (name) VALUES ('Service Design Tools');
INSERT INTO book_booktopic (name) VALUES ('Design tools');
INSERT INTO book_booktopic (name) VALUES ('Design theory / systems');
INSERT INTO book_booktopic (name) VALUES ('Systems thinking');
INSERT INTO book_booktopic (name) VALUES ('UX storytelling');
INSERT INTO book_booktopic (name) VALUES ('Design thinking');
